import { useState, useEffect } from "react";
import { ChevronDown, ChevronUp, Calendar, Activity } from "lucide-react";

type EmotionType = "calm" | "anxious" | "excited" | "sad";

interface TimelineEvent {
  id: string;
  time: string;
  emotion: string; // The backend might send "STRESSED"
  label: string;   // The Kaggle AI sends "angry", "fearful", etc.
  avgHR: number;
  avgGSR: number;
  avgIMU: number;
  transcript: string;
}

const emotionColors: Record<EmotionType, string> = {
  calm: "bg-emotion-calm",
  anxious: "bg-emotion-anxious",
  excited: "bg-emotion-excited",
  sad: "bg-emotion-sad",
};

const emotionTextColors: Record<EmotionType, string> = {
  calm: "text-emotion-calm",
  anxious: "text-emotion-anxious",
  excited: "text-emotion-excited",
  sad: "text-emotion-sad",
};

// Maps the Kaggle AI's raw output to your UI's color themes
const mapToTheme = (aiLabel: string): EmotionType => {
  const label = aiLabel.toLowerCase();
  if (["angry", "fearful", "disgust", "stressed"].includes(label)) return "anxious";
  if (["happy", "surprised"].includes(label)) return "excited";
  if (["sad"].includes(label)) return "sad";
  return "calm"; // covers "neutral", "calm", etc.
};

export default function ReflectionTimeline() {
  const [expandedIds, setExpandedIds] = useState<Set<string>>(new Set());
  const [events, setEvents] = useState<TimelineEvent[]>([]);
  const [isConnected, setIsConnected] = useState(false);

  const toggleExpand = (id: string) => {
    setExpandedIds((prev) => {
      const next = new Set(prev);
      if (next.has(id)) next.delete(id);
      else next.add(id);
      return next;
    });
  };

  // POLLING LOGIC: Reads the history file generated by the Python Brain
  useEffect(() => {
    const fetchHistory = async () => {
      try {
        const response = await fetch("/data/emotion_history.json");
        if (!response.ok) throw new Error("History file not found");
        
        const data = await response.json();
        setEvents([...data].reverse()); // Put newest events at the top
        setIsConnected(true);
      } catch (error) {
        setIsConnected(false);
        // Silently fail if file isn't ready yet
      }
    };

    fetchHistory();
    const interval = setInterval(fetchHistory, 2000); // Check for new events every 2 seconds
    return () => clearInterval(interval);
  }, []);

  return (
    <div className="max-w-4xl mx-auto space-y-6 animate-fade-in-up pb-12">
      {/* Header */}
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-xl font-semibold text-foreground tracking-tight flex items-center gap-2">
            Emotional Reflection Log
            {/* Added a tiny live indicator next to the title */}
            <div className={`h-2 w-2 rounded-full ${isConnected ? 'bg-green-500 animate-pulse' : 'bg-red-500'}`} />
          </h1>
          <p className="text-sm text-muted-foreground">
            {isConnected ? "Live syncing with Brain..." : "Waiting for connection..."}
          </p>
        </div>
        <button className="flex items-center gap-2 px-3 py-2 rounded-lg border border-border bg-card text-sm text-foreground hover:border-primary/40 transition-colors">
          <Calendar className="h-3.5 w-3.5 text-muted-foreground" />
          Today
        </button>
      </div>

      {/* Empty State when connected but no spikes have happened */}
      {events.length === 0 && isConnected && (
        <div className="text-center p-12 border border-dashed border-border rounded-xl mt-8">
          <Activity className="h-8 w-8 mx-auto text-muted-foreground mb-3 opacity-50" />
          <p className="text-muted-foreground text-sm">Listening for biometric spikes...</p>
        </div>
      )}

      {/* Timeline */}
      {events.length > 0 && (
        <div className="relative">
          {/* Vertical line */}
          <div className="absolute left-[88px] top-0 bottom-0 w-px bg-border" />

          <div className="space-y-6">
            {events.map((event) => {
              const isExpanded = expandedIds.has(event.id);
              const theme = mapToTheme(event.label); // Convert AI label to UI color

              return (
                <div key={event.id} className="flex gap-4 items-start">
                  {/* Time */}
                  <div className="w-20 shrink-0 text-right pt-1">
                    <span className="text-xs font-mono text-muted-foreground">{event.time}</span>
                  </div>

                  {/* Dot */}
                  <div className="relative z-10 mt-1.5 shrink-0">
                    <div className={`h-3 w-3 rounded-full ${emotionColors[theme]} ring-4 ring-background`} />
                  </div>

                  {/* Detail Card */}
                  <div className="flex-1 card-gradient rounded-lg border border-border p-4 glow-border hover:border-primary/20 transition-all">
                    <div className="flex items-center justify-between mb-2">
                      <span className={`text-sm font-semibold uppercase tracking-wider ${emotionTextColors[theme]}`}>
                        {event.label}
                      </span>
                    </div>

                    <div className="flex gap-4 text-xs text-muted-foreground mb-3">
                      <span>Avg HR: <span className="text-foreground font-mono">{event.avgHR}</span> BPM</span>
                      <span>GSR: <span className="text-foreground font-mono">{event.avgGSR}</span> µS</span>
                      <span>IMU: <span className="text-foreground font-mono">{event.avgIMU}</span> g</span>
                    </div>

                    <div>
                      <button
                        onClick={() => toggleExpand(event.id)}
                        className="flex items-center gap-1 text-xs text-muted-foreground hover:text-foreground transition-colors mb-1"
                      >
                        Audio Transcript
                        {isExpanded ? <ChevronUp className="h-3 w-3" /> : <ChevronDown className="h-3 w-3" />}
                      </button>
                      <p className="text-sm text-secondary-foreground leading-relaxed italic">
                        "{isExpanded
                          ? event.transcript
                          : event.transcript.slice(0, 80) + (event.transcript.length > 80 ? "…" : "")}"
                      </p>
                    </div>
                  </div>
                </div>
              );
            })}
          </div>
        </div>
      )}
    </div>
  );
}